services:
  db:
    image: postgres:16
    container_name: expense-tracker-postgres-16
    command: "postgres -c 'max_connections=100'"
    env_file:
      - .db.env
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web_app.dev
    container_name: expense_tracker_web_container
    depends_on:
      - redis
      - db
    env_file:
      - .dev.env
    ports:
      - "3010:3010"
    tty: true
    volumes:
      - .:/rails
volumes:
  postgres_data: {}
