# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.3.4
FROM ruby:$RUBY_VERSION-slim as base

# Rails app lives here
WORKDIR /rails

# Set development environment
ENV BUNDLE_WITHOUT="" \
    RAILS_ENV="development"

# Update gems and bundler
RUN gem update --system --no-document && \
    gem install -N bundler && \
    gem install foreman

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential libpq-dev libvips

# Install editor for convenience
RUN apt-get install --no-install-recommends -y neovim

# Install application gems
COPY --link Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY --link . .

# Precompile bootsnap code for faster boot times
# RUN bundle exec bootsnap precompile app/ lib/

# Run and own only the runtime files as a non-root user for security
# RUN groupadd --system --gid 1000 rails && \
#     useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
#     chown -R 1000:1000 db log storage tmp
# USER 1000:1000

# Deployment options
ENV RAILS_LOG_TO_STDOUT="1" \
    RAILS_SERVE_STATIC_FILES="true"

# Entrypoint sets up the container.
ENTRYPOINT ["/rails/bin/docker-entrypoint.dev"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3010
