default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') { 'expense_tracker_development' } %>
  host: <%= ENV.fetch('DB_HOST') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>

test:
  <<: *default
  database: expense_tracker_test

production:
  <<: *default
  database: expense_tracker_production
